version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USERNAME: root
      DB_PASSWORD: golfpativat719
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: shopping
      JWT_SECRET: "wBf5qT9z@C#G&E)J-Md2PgU$dR@N*7L!"

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: golfpativat719
      MYSQL_DATABASE: shopping
