package main

import (
	"go_gin/configs"
	controllerproduct "go_gin/controller/ControllerProduct"
	controlleruser "go_gin/controller/ControllerUser"
	"go_gin/database"
	_ "go_gin/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Gin Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
func main() {
	r := gin.Default()

	configs.Init()
	database.ConnectMySQL()

	// Product
	r.GET("/product/all", controllerproduct.GetAllProduct)
	r.GET("/product/all/filter", controllerproduct.GetProduct)
	r.POST("/product/insert", controllerproduct.InsertProduct)

	// User
	r.GET("/user/all", controlleruser.GetAllUser)
	r.GET("/user/all/filter", controlleruser.GetUser)
	r.POST("/user/insert", controlleruser.InsertUser)

	//Category

	// Swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":8080")
}
